version: '3'
services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  balance:
    build:
      context: ./services/balance
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
  transaction:
    build:
      context: ./services/transaction
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
